apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zk-tls
spec:
  secretName: zk-tls-secret
  duration: 2160h
  renewBefore: 360h
  commonName: zookeeper.default.svc.cluster.local
  dnsNames:
  - zookeeper.default.svc.cluster.local
  issuerRef:
    name: zk-issuer
    kind: Issuer
